# Generated by Django 2.1.5 on 2019-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewBeforeYouBuy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_price', models.CharField(max_length=50)),
                ('c_photo_link', models.CharField(max_length=50)),
                ('c_content_link', models.CharField(max_length=50)),
                ('c_feedback_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Hardware',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=50)),
                ('h_price', models.CharField(max_length=50)),
                ('h_photo_link', models.CharField(max_length=50)),
                ('h_content_link', models.CharField(max_length=50)),
                ('h_feedback_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_Accessory',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=50)),
                ('e_price', models.CharField(max_length=50)),
                ('e_photo_link', models.CharField(max_length=50)),
                ('e_content_link', models.CharField(max_length=50)),
                ('e_feedback_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=50)),
                ('l_price', models.CharField(max_length=50)),
                ('l_photo_link', models.CharField(max_length=50)),
                ('l_content_link', models.CharField(max_length=50)),
                ('l_feedback_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=50)),
                ('m_price', models.CharField(max_length=50)),
                ('m_photo_link', models.CharField(max_length=50)),
                ('m_content_link', models.CharField(max_length=50)),
                ('m_feedback_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Smart_Watches',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('s_price', models.CharField(max_length=50)),
                ('s_photo_link', models.CharField(max_length=50)),
                ('s_content_link', models.CharField(max_length=50)),
                ('s_feedback_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mnumber', models.CharField(max_length=50)),
            ],
        ),
    ]
